### ISSUE TITLE
Why cant we use non hardened derivation paths ?

### ISSUE THREAD

**Issue by Ch1p999** [alepop/ed25519-hd-key#1]
Not working !
ie.
```
var { key, chainCode} = derivePath("m/0/0", hexSeed);
```

**Comment by alepop** [comment]
@Ch1p999 please provide additional info, logs. 
Also, as I see, you try to use none derived paths and this is not possible for `ed25519` based on [SLIP-0010](https://github.com/satoshilabs/slips/blob/master/slip-0010.md)
try this `var { key, chainCode} = derivePath("m/0'/0'", hexSeed);`

**Comment by anarkrypto** [comment]
> @Ch1p999 please provide additional info, logs. Also, as I see, you try to use none derived paths and this is not possible for `ed25519` based on [SLIP-0010](https://github.com/satoshilabs/slips/blob/master/slip-0010.md) try this `var { key, chainCode} = derivePath("m/0'/0'", hexSeed);`
> 
> Update: Sorry, didn't look at issue description subject. Non-hardened derivation paths are not possible for ed25519.

Actually, It's possible
https://crypto.stackexchange.com/questions/66793/is-it-possible-to-derive-a-public-key-from-another-public-key-without-knowing-a

**Comment by alepop** [comment]
@anarkrypto I would be appreciated for a pull request with this functionality. Of course If you want.

**Comment by anarkrypto** [comment]
@alepop, funny... according to chat-gpt your package already does that haha
![image](https://user-images.githubusercontent.com/32111208/222063903-b8b8653b-edda-42a9-a6ae-136a133dfe35.png)
