### ISSUE TITLE
Derive path using extended public key

### ISSUE THREAD

**Issue by ppoliani** [alepop/ed25519-hd-key#237]
I just looked into the code and noticed that there is function that allows to derive private keys. I wonder if it's possible to derive plublic keys by providing an xpub.

Something like this, for example:

`const derivePath = (path, xpub) => {}`

**Comment by getlarge** [comment]
I was asking myself the same question, it seems unsupported for ed25519. Read [this SLIP-10 section](https://github.com/satoshilabs/slips/blob/master/slip-0010.md#public-parent-key--public-child-key).

**Comment by alepop** [comment]
@ppoliani thanks for opening the issue. As @getlarge wrote this feature is not supported.
