### ISSUE TITLE
different result compared to hdkey package

### ISSUE THREAD

**Issue by yurenji** [alepop/ed25519-hd-key#254]
(I am not sure if this is the right place to ask the question, but couldn't get anyone to help me with this now. )

I tried the following process: 

```
const bip39 = require("bip39");
const HDKey = require("hdkey");
const { derivePath, getMasterKeyFromSeed, getPublicKey } = require('ed25519-hd-key')

const mnemonic = bip39.generateMnemonic()
const hexSeed = bip39.mnemonicToSeedSync(mnemonic, "");
// pubkey1 
var hdkey = HDKey.fromMasterSeed(hexSeed);
console.log(hdkey.publicKey.toString('hex'));
// pubkey2 
const { key, chainCode } = getMasterKeyFromSeed(hexSeed);
console.log(getPublicKey(key).toString('hex'))
```

but got 2 different public keys: 
```
033d14e8dcf3173b485e5eb06705d36ae0de8068ecf458eec23fb4c65177c6fea6
006ca3bbaee78fdc7e878985ed1c288db7ef52669ffea9547093dc722f75bbf402
```

Can anyone help me understand why the result is different?

**Comment by alepop** [comment]
Hi @yurenji.
First of all don't worry, this implementation works fine. library uses original test vector cases from original BIP and all tests is green. 
`hdkey` library target on key derivation for `secp256k1` curve, meanwhile my library target on `ed25519` curve key derivation. Based on [SLIP-0010](https://github.com/satoshilabs/slips/blob/master/slip-0010.md) they have different curve seed and because of this you've got a different results.
```
Curve = "Bitcoin seed" for the secp256k1 curve (this is compatible to BIP-0032).
Curve = "ed25519 seed" for the ed25519 curve.
```
Hope that I answered your question

**Comment by yurenji** [comment]
Thanks for the help, it explains well. I have a further question: 

Running the following code: 
```
const bip39 = require("bip39");
const { derivePath, getMasterKeyFromSeed, getPublicKey } = require('ed25519-hd-key')
const mnemonic = bip39.generateMnemonic()
console.log("mnemonic: "+mnemonic)
const hexSeed = bip39.mnemonicToSeedSync(mnemonic, "");
const { key, chainCode } = getMasterKeyFromSeed(hexSeed);
console.log("pubkey: "+getPublicKey(key).toString('hex'))
```
Outputs: 
```
mnemonic: raccoon avocado hurt give raw orchard album believe jaguar what ability gas
pubkey: 00d11b7859057d14a1694a03172574ea40f3b38842b0c4e6757e86c29b639397cf
```

However, if I use another tool (solana-cli) to recover pubkey from mnemonic and passphrase, I got a different result. 

```
➜ solana-keygen recover -o ~/solana/test.json
[recover] seed phrase: raccoon avocado hurt give raw orchard album believe jaguar what ability gas
[recover] If this seed phrase has an associated passphrase, enter it now. Otherwise, press ENTER to continue:
Recovered pubkey `5cXxCEwHw5bmpnPKjttzg8FBniWSbXkAkku2okhyYfjj`. 
```

I am confused since the most popular solana wallet (sollet.io) [uses ed25519-hd-key](https://github.com/project-serum/spl-token-wallet/blob/master/package.json#L25), the solana-sdk also uses [ed25519-dalek](https://github.com/solana-labs/solana/blob/master/sdk/Cargo.toml#L31). 

Do you know what might cause the different result/pubkey? 

Thanks in advance.
