### ISSUE TITLE
TypeError: Cannot read property 'crypto_sign_seed_keypair' of undefined

### ISSUE THREAD

**Issue by sundaywork** [alepop/ed25519-hd-key#39]
Multiple TypeError: Cannot read property 'crypto_sign_seed_keypair' of undefined error. Have no idea how to fix...

> npm test

> ed25519-hd-key@1.0.0 test ...
> jest

 FAIL  src\index.spec.ts
  Test vectors
    Vector 1
      √ should have valid keys for vector 1 seed hex (3ms)
      × should valid for m/0' (121ms)
      × should valid for m/0'/1'
      × should valid for m/0'/1'/2'
      × should valid for m/0'/1'/2'/2' (1ms)
      × should valid for m/0'/1'/2'/2'/1000000000'
    Vector 2
      √ should have valid keys for vector 2 seed hex
      × should valid for m/0' (1ms)
      × should valid for m/0'/2147483647'
      × should valid for m/0'/2147483647'/1'
      × should valid for m/0'/2147483647'/1'/2147483646' (1ms)
      × should valid for m/0'/2147483647'/1'/2147483646'/2'

  ● Test vectors › Vector 1 › should valid for m/0'

    TypeError: Cannot read property 'crypto_sign_seed_keypair' of undefined

      at Object.<anonymous>.exports.getPublicKey (src/index.ts:54:37)
      at Object.it (src/index.spec.ts:114:32)
          at new Promise (<anonymous>)
      at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by alepop** [comment]
@sundaywork first of all, thank for using my library. Problem was with not exact dependencies version in `package.json` file. Now it's fixed

**Comment by sundaywork** [comment]
Hi Alepop,

How can I use the library in browser? I have been trying for 2 days but
can't get it through. Trying to use webpack to build and it passes, but
when load in the html it always get this:
[image: image.png]
It looks like coming from the createHmac library but I have no idea how to
get it to work. Do you have any other suggestions on how to get it running
in the browser? Thanks a lot

**Comment by alepop** [comment]
@sundaywork please upload the image or provide a link for it.

**Comment by sundaywork** [comment]
I've found the problem. It was wrong in my webpack config file. Thanks.

Additional question:
When you createHmac from the seed, is that 'ed25519 seed' is used as the initial key?
const hmac = createHmac('sha512', ED25519_CURVE);

**Comment by alepop** [comment]
@sundaywork hey! All details about how it works you can find in [https://github.com/satoshilabs/slips/blob/master/slip-0010.md#master-key-generation](specification)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
